runtime: nodejs10

instance_class: F1
automatic_scaling:
  max_instances: 1

handlers:
  - url: .*
    secure: always
    script: auto

env_variables:
  MONGO_CONNECTION: "mongodb+srv://areef:Krokus@cluster0.ifgem.mongodb.net/test"
  API_SECRET: "genepathdiag"
  DEVICESTATUS_ADVANCED: "true"
  ENABLE: "careportal rawbg food sage"
  DISABLE: "upbat"
  DISPLAY: "unfiltered"
  BG_TARGET_TOP: "140"
  BG_TARGET_BOTTOM: "70"
  BASE_URL: "https://geneclinicx.el.r.appspot.com"
